### ISSUE TITLE
How to configure without VScode. 

### ISSUE THREAD

**Issue by Numkil** [moetelo/twiggy#12]
Hiya, 

I've been happily using twiggy as an LSP in neovim for a bit now. I saw in the latest release that support for CraftCMS has been added but that you need to set a few options for it to work. 

I couldn't figure out how to configure the language server in neovim though. Can I add the framework option by appending it to the cmd "twiggy-language-server", "--stdio"? 

If not could you explain how to configure your LSP? thank you!

**Comment by moetelo** [comment]
Hello!

Please follow the language server output, it should guide you through the configuration process.

`vim.lsp.set_log_level('warn')`

`:LspLog`

---

https://github.com/moetelo/twiggy/blob/40c0c45684808bf972af7a3fb9e30494437f3c16/packages/vscode/package.json#L64-L85
These settings are required from now.

Here is an example configuration for NVChad:

```lua
lspconfig.twiggy_language_server.setup {
    on_attach = on_attach,
    capabilities = capabilities,
    settings = {
        twiggy = {
            -- before 0.8.0:
            -- phpBinConsoleCommand = 'php-legacy bin/console',
            framework = 'symfony',
            phpExecutable = '/usr/bin/php-legacy',
            symfonyConsolePath = 'bin/console',
        },
    },
}
```

**Comment by Numkil** [comment]
Wow thank you for the elaborate reply! That really helped. Ill close this issue now :)

**Comment by kekkoudesu** [comment]
@moetelo Not sure if you wanted these instructions in a markdown file somewhere in the repository (I can make a PR), but here's what I had to do to setup Twiggy with Neovim today, using the built-in LSP config (no plugins required):

```
  vim.lsp.config["twiggy-language-server"] = {
    cmd = { "twiggy-language-server", "--stdio" },
    root_markers = { 'composer.json' },
    filetypes = { 'twig' },
    settings = {
              twiggy = {
                      framework = 'symfony',
                      phpExecutable = '/usr/bin/php',
                      symfonyConsolePath = 'bin/console',
                      diagnostics = {
                              twigCsFixer = true,
                      },
              },
    },
  }
  vim.lsp.enable({'twiggy-language-server'})
  vim.api.nvim_create_autocmd('LspAttach', {
        callback = function(ev)
        local client = vim.lsp.get_client_by_id(ev.data.client_id)
        if client:supports_method('textDocument/completion') then
                vim.lsp.completion.enable(true, client.id, ev.buf, {autotrigger = true})
        end
  end,
  })
```

The additional `diagnostics` key is now required for Twiggy to start. I'm not sure if I need to have Twig CS Fixer installed separately for Twiggy to use it but it doesn't seem to hit any errors aside from these:

```
[WARN][2025-07-06 15:40:09] ...m/lsp/client.lua:874	"The language server twiggy-language-server triggers a registerCapability handler for workspace/didChangeConfiguration despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[WARN][2025-07-06 15:40:09] ...lsp/handlers.lua:564	'Symfony console path "bin/console" does not exist'
```

Twiggy then works on `.twig` files. Though annoyingly, when I complete snippets like `extends`, I get this:

```
{{% extends '' %}
```

The extra `{` then needs to be deleted. Not sure if this is an issue with Neovim or Twiggy.

Hope this helps someone.
