### ISSUE TITLE
Add Neovim configuration guide to README.md

### ISSUE THREAD

**Issue by moetelo** [moetelo/twiggy#13]
Refactor this reply https://github.com/moetelo/twiggy/issues/12#issuecomment-2044309054 into something README-friendly and add it somewhere here, after the VS Code setup guide:

https://github.com/moetelo/twiggy/blob/40c0c45684808bf972af7a3fb9e30494437f3c16/README.md?plain=1#L22-L27

**Comment by gubler** [comment]
One thing that would help with this would be adding this LSP to the Mason Registry. Mason is used in a lot of people's config's for auto-installing/setup of LSPs.

https://github.com/mason-org/mason-registry

**Comment by moetelo** [comment]
@gubler Already there:

https://github.com/mason-org/mason-registry/blob/646d547647c136f8b1f47d3b8acefa5ded8c4c12/packages/twiggy-language-server/package.yaml

**Comment by gubler** [comment]
@moetelo My apologies - I looked and completely missed it...
