### ISSUE TITLE
Support goto definition for macro imports

### ISSUE THREAD

**Issue by aszenz** [moetelo/twiggy#17]
```
    {% import 'ComponentShowcase/lib.html.twig' as lib %}
    {{ lib.html_component_example(component, "Basic") }}
```

**Comment by moetelo** [comment]
If I ctrl+click the `my_macro`, the editor correctly opens the `macroses.html.twig` template.

![image](https://github.com/moetelo/twiggy/assets/17011936/66bf3ce7-9ae1-4eb7-9a27-94f629e1ffc6)

Could you provide more details on this?

**Comment by aszenz** [comment]
> If I ctrl+click the my_macro, the editor correctly opens the macroses.html.twig template.

Correct, sorry i should have provided a more specific example.

This is the example not working for me, the import is inside a macro, since macros cannot use imports from their parent (see https://github.com/twigphp/Twig/issues/3640#issuecomment-1030667651), we need to re-import them inside a macro.

```twig
{% macro test() %}
    {% import 'components.html.twig' as components %}
    {{ components.menu() }} {# Goto definition doesn't work here #}
{% endmacro %}
```
