### ISSUE TITLE
[BUG] Cannot set `twiggy.phpBinConsoleCommand`

### ISSUE THREAD

**Issue by YummYume** [moetelo/twiggy#3]
Hello! Thank you so much for this, it was much needed in the Twig development world.

I don't seem to be able to set the `twiggy.phpBinConsoleCommand` as told in the documentation, I get an error whenever I try to do so. I tried on multiple projects, with and without VSCode insiders and with relative/absolute paths. Ultimately, it either fails to find my bin/console file, or it finds it but crashes.

On a clean project with using a VSCode workspace and an absolute path, I got the following : 

```bash
[Error - 10:10:32 PM] Server initialization failed.
Error: command 'twiggy.is-inside-html-region' already exists
    at n.registerCommand (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:125:85649)
```

On another pretty big project without any workspace and using a relative path (simply `php bin/console`), I get : 

```bash
TypeError: Cannot read properties of null (reading 'map')
    at Ah (/home/.../.vscode-insiders/extensions/moetelo.twiggy-0.5.9/dist/server.js:118:61786)
```

It is worth noting that all these projects are using Docker, but I can run `php bin/console` outside the containers just fine, it still works.

NOTE : When I first installed this extension, I was able to get autocompletion when writing set, if, etc... Just fine. After I tried to set `twiggy.phpBinConsoleCommand`, the server would just crash and not give me autocompletion any more, even after I completely removed the setting and reinstalled the extension. However, CTRL + click on file paths and variables still works.

**Comment by moetelo** [comment]
Hello @YummYume, thank you for your feedback!
Please, check out the latest release. I've fixed some of the multi-folder workspace related issues, so that might work for you.

**Comment by moetelo** [comment]
Hello @YummYume, thank you for your feedback!
Please, check out the latest release. I've fixed some of the multi-folder workspace related issues, so that might work for you.

**Comment by YummYume** [comment]
@moetelo Hi! Thanks for your quick answer, it seems to work very well now. Thank you!
