### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined method ReflectionUnionType::getName()

### ISSUE THREAD

**Issue by ging-dev** [moetelo/twiggy#31]
https://github.com/moetelo/twiggy/blob/7099a67eb33a8f687ccfc726cce7b70ce734c435/packages/language-server/phpUtils/completeInstanceProperties.php#L48-L63

`$method->getReturnType()` and `$parameter->getType()` can return `ReflectionUnionType` or `ReflectionIntersectionType` which doesn't have getName method. Personally, I think we should find a library that can extract information better, such as supporting phpdoc, but it seems a bit difficult.

**Comment by moetelo** [comment]
Stumbled upon this bug once and had the fix uncommited in some forgotten branch.

**Comment by moetelo** [comment]
> a library that can extract information better

Are you suggesting to add a JS library, something like [php-parser](https://www.npmjs.com/package/php-parser)?

While I'm trying to keep the extension size as small as possible, I think at some time I'll have to add that lib to support more advanced features...

**Comment by ging-dev** [comment]
> > a library that can extract information better
> 
> Are you suggesting to add a JS library, something like [php-parser](https://www.npmjs.com/package/php-parser)?
> 
> While I'm trying to keep the extension size as small as possible, I think at some time I'll have to add that lib to support more advanced features...

I mean besides native type hint, some phpdoc annotations like `@param`, `@return` are also used, and we are missing support for them, probably something like `phpdoc-parser`, but it seems complicated to implement.
