### ISSUE TITLE
Add some settings to customize phpUtils

### ISSUE THREAD

**Issue by ging-dev** [moetelo/twiggy#32]
Customizing the path of the *.php file can help users create their own suggestions as desired.
https://github.com/moetelo/twiggy/tree/master/packages/language-server/phpUtils

**Comment by moetelo** [comment]
I don't get the idea

Could you describe a user scenario?

**Comment by ging-dev** [comment]
> I don't get the idea
> 
> Could you describe a user scenario?

The idea is to allow users to override the path to the php file. eg: instead https://github.com/moetelo/twiggy/blob/master/packages/language-server/phpUtils/reflectType.php, users can set a path to their own php file (i.e: /path/custom_suggestion.php) to generate their own custom code suggestions.

**Comment by moetelo** [comment]
What's the example use case for this?

> their own custom code suggestions

Like what?

Personally I prefer the way of adding as much as we can to the language server itself, so that the end user doesn't have to customize anything.
