### ISSUE TITLE
Getting "Document text is not set" error

### ISSUE THREAD

**Issue by BladeMF** [moetelo/twiggy#34]
Since the last version, while typing in a twig file I keep getting this error:

```
[Error - 5:50:14 AM] Request workspace/executeCommand failed.
  Message: Request workspace/executeCommand failed with message: Document text is not set. File: /var/www/html/app/src/UI/Symfony/Tenders/Views/search@form.html.twig
  Code: -32603
```

There is nothing special about the file or the project. I've been working on it for a month. It started today.

**Comment by moetelo** [comment]
kinda reproduced the error, but it happens randomly

please ping me if this was fixed or not for your case

**Comment by BladeMF** [comment]
It seems solved for now, but I haven't been working on a twig today or yesterday.
