### ISSUE TITLE
stdout maxBuffer length exceeded

### ISSUE THREAD

**Issue by martijn-dd** [moetelo/twiggy#44]
Hello,

I have an issue with Twiggy and Shopware 6 in VsCode as with Neovim.
For both editors I've modified the framework, php bin and console command.
But with both editors functionality is limited with this combination. Like clicking on the path of an 'extends' file.
In the LSP log I get the same error in both editors:

**VsCode:**
[Error - 12:14:09] stdout maxBuffer length exceeded
[Error - 12:14:09] {
    "api.action.access-key.integration": {
        "path": "\/api\/_action\/access-key\/intergration",
        "pathRegex": "{^\/api\/_action\/access\\-key\/intergration$}sDu",
...

**Neovim**:

[ERROR][2024-10-14 12:06:23] ...lsp/handlers.lua:623	"stdout maxBuffer length exceeded"
[ERROR][2024-10-14 12:06:23] ...lsp/handlers.lua:623	'{\n    "api.action.access-key.integration": {\n        "path": "\\/api\\/_action\\/access-key\\/intergration",\n      
...

It looks like I get this error when it executes the console commands.
My guess is that the output of bin/console debug:router --format json is the issue.
When I run this command in my terminal and save the output to a json file it is ~1.8MB

The output of the debug:router seems good, it's just very large in Shopware.

What can I do to make this work with Shopware?
Or did anybody else ran into this issue?

**Comment by moetelo** [comment]
Wow. I need some way to reproduce this.

**Comment by martijn-dd** [comment]
On my mac I use devenv to setup Shopware.
But with Docker is also an option:

[https://developer.shopware.com/docs/guides/installation/community/dockware.html](https://developer.shopware.com/docs/guides/installation/community/dockware.html)

I can also send the a json file with the output.
Or that I use the pnpm install with the F5 debug to see where it crashes.
May need a little of guiding which files to debug.

Not sure if child_process is used but looks like a maxBuffer option can be added:
[https://nodejs.org/api/child_process.html#child_processexeccommand-options-callback](https://nodejs.org/api/child_process.html#child_processexeccommand-options-callback)

**Comment by moetelo** [comment]
Done all the steps [here](https://developer.shopware.com/docs/guides/installation/community/dockware.html#using-docker-compose), in the compose section. Getting not much of the output, only 16K.

```bash
$ php bin/console debug:twig --format json > output.json
Warning: Failed to load plugins. Message: An exception occurred in the driver: could not find driver
Warning: Failed to load apps. Loading apps from local. Message: An exception occurred in the driver: could not find driver

$ du -sh output.json                                          
16K     output.json
```

Thus, the completion works fine.

> I can also send the a json file with the output.

That would be great

**Comment by martijn-dd** [comment]
The output of debug:twig is also not that large at my project. The large one is php bin/console debug:router --format json.
I've added two json files for the debug:twig and debug:router command from a recent Shopware 6.6 shop.

```
$ du -sh twig_output.json
16K    twig_output.json

$ du -sh router_output.json
2,5M    router_output.json
```

[router_output.json](https://github.com/user-attachments/files/17504417/router_output.json)
[twig_output.json](https://github.com/user-attachments/files/17504418/twig_output.json)

**Comment by martijn-dd** [comment]
And the LSP log when I open a twig file:

[12-Twiggy Language Server.log](https://github.com/user-attachments/files/17504594/12-Twiggy.Language.Server.log)

**Comment by moetelo** [comment]
It seems that simply increasing `maxBuffer` [here](https://github.com/moetelo/twiggy/blob/9387645a2a862e9d2af75461fe6803e557e486c6/packages/language-server/src/utils/exec.ts#L12-L14) could help, as it [defaults to 1MB](https://nodejs.org/api/child_process.html#child_processexeccommand-options-callback).

As far as I understand, this doesn't contribute to the memory usage of the language server; it only sets a cap on how much output data can be buffered in memory before it's handled.

So, something like this will do the trick:

```ts
export const exec = (cmd: string): Promise<{ stdout: string, stderr: string }> => {
    return execPromisified(cmd, {
        maxBuffer: 1024 * 1024 * 3, // 3MB
    }).catch((err) => ({ stdout: '', stderr: err.message }))
};
```

**Comment by martijn-dd** [comment]
Thank you for the quick response and fix.
