### ISSUE TITLE
Twig Language Server fails when XDebug is enabled from php.ini

### ISSUE THREAD

**Issue by Eptagone** [moetelo/twiggy#6]
Hi. This is probably the best Twig extension until now, so thank you very much.
I noticed the extension fails if XDebug is enabled from `php.ini` file.
My current `php.ini` have these lines.
```ini
# php.ini
; XDEBUG CONFIGURATION
zend_extension="xdebug.so"
xdebug.mode=debug,develop
xdebug.start_with_request=yes
xdebug.idekey=VSCODE
```

Every time I open my project folder, **Twig Language Server** always fails:
```log
Language server started for: /home/eptadot/source/my-symfony-pro
Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9003 (through xdebug.client_host/xdebug.client_port).
Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9003 (through xdebug.client_host/xdebug.client_port).
Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9003 (through xdebug.client_host/xdebug.client_port).
Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9003 (through xdebug.client_host/xdebug.client_port).
Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9003 (through xdebug.client_host/xdebug.client_port).
Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9003 (through xdebug.client_host/xdebug.client_port).
Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9003 (through xdebug.client_host/xdebug.client_port).
Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9003 (through xdebug.client_host/xdebug.client_port).
Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9003 (through xdebug.client_host/xdebug.client_port).
Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9003 (through xdebug.client_host/xdebug.client_port).
Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9003 (through xdebug.client_host/xdebug.client_port).
Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9003 (through xdebug.client_host/xdebug.client_port).
Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9003 (through xdebug.client_host/xdebug.client_port).
Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9003 (through xdebug.client_host/xdebug.client_port).
Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9003 (through xdebug.client_host/xdebug.client_port).

Could not collect any information from the output of the 'php bin/console debug:twig --format json'. Either the project doesn't use Symfony or the command is not correct.
```

That's because **XDebug** log messages like these before and after a command if the debugger is not connected to VS Code yet.
![image](https://github.com/moetelo/twiggy/assets/23562885/5250f4a7-f97e-489d-89f9-fae6145a80cc)
Because that I guess the JSON cannot be parsed or something because if I disable **XDebug** then it works again.

It would be great if the extension could handle these outputs or at least add a command to reload the **Twig Language Server**.
Some extensions offer commands like that. These are some examples:
![image](https://github.com/moetelo/twiggy/assets/23562885/c96c7931-43e1-4c36-9710-e916318e417d)
![image](https://github.com/moetelo/twiggy/assets/23562885/c403808a-27bf-45ba-a4b4-519be84c4a8c)

**Comment by moetelo** [comment]
Could you provide an example project that I can clone and play with, so I can reproduce this issue?

**Comment by moetelo** [comment]
To reproduce the issue, these variables must also be empty.

```ini
xdebug.log=
error_log=
```

**Comment by Eptagone** [comment]
Hi @moetelo. I'm having the same issue when using deprecated features in new versions of PHP. Can this issue be re-open or should I create a new one?

EXTENSION OUTPUT
<img width="1209" alt="Image" src="https://github.com/user-attachments/assets/8673b1e8-467d-47e0-ace7-f8b5f683e045" />

It happen because a vendor dependency, the deprecations messages appears before the JSON

<img width="1601" alt="Image" src="https://github.com/user-attachments/assets/f6c67f46-6ec8-436d-a8ee-d47458cb3993" />

<img width="1411" alt="Image" src="https://github.com/user-attachments/assets/a9e01a07-0d7c-4498-92be-12cbd953a836" />

This is an example of deprecated code when using PHP 8.4
```php
public function run(InputInterface $input = null, OutputInterface $output = null)
{
    // ...
}
```
To fix the deprecation, the nullable `?` should be added like this:
```
public function run(?InputInterface $input = null, ?OutputInterface $output = null)
{
    // ...
}
```
But I can't fix the code because it's a dependency
