### ISSUE TITLE
Expose language server as binary

### ISSUE THREAD

**Issue by niksy** [moetelo/twiggy#7]
Can language server be exposed as binary so it can be installed globally and then used in other editor’s client implementations such as Sublime LSP?

See TypeScript Language Server implementation: https://github.com/typescript-language-server/typescript-language-server/blob/master/package.json#L18-L20

**Comment by moetelo** [comment]
Done, now the `npx twiggy-language-server --stdio` command works correctly. Thank you!

**Comment by moetelo** [comment]
@niksy 
Yep, I've mistakenly used the pnpx command instead of npx.

Not sure why is that happening. Will investigate later. For now, you can use the pnpm's command, if that's ok for you:
`pnpm dlx twiggy-language-server --stdio`

**Comment by niksy** [comment]
I’ve managed to start it for Sublime LSP, but I get following error on empty Twig document:

```
:: [09:05:10.323] <~~ LSP-twig (1) (duration: 48ms): {'message': "Request initialize failed with message: Cannot read properties of null (reading '0')", 'code': -32603}
```
This happens if I’m not using projects/workspaces.
I think this is related to settings passed on to server, but can’t figure out what.

Is there something else that needs to be added to initialization logic?

---

If I create project/workspace, I get the following error:

```
LSP: LSP-twig crashed (1 / 5 times in the last 180.0 seconds), exit code 0, exception: Unexpected payload in server's stdout:


The `twiggy.phpBinConsoleCommand` setting is empty. If your project uses Symfony, please set it in the extension settings for better language server features.
Content-Length: 149
```

I don’t have Symfony project so I want to skip PHP bin console command setup. If I set it to some basic value like `echo 1`, error disappears, but server seems to be doing nothing even though it receives all the necessary events:

![Screenshot 2024-03-18 at 09 19 46](https://github.com/moetelo/twiggy/assets/389286/dfdaf58b-e2d3-4351-a6c0-b768f06032a9)

---

I know it’s not grateful to ask for Sublime Text support when this is primarily VS Code related tool, but having editor-agnostic server implementation will greatly help other editors with LSP implementations if we can get it working everywhere :)

**Comment by moetelo** [comment]
@niksy 
> not grateful to ask for Sublime Text support when this is primarily VS Code related tool

That's totally ok! This is a vscode-only tool just because I didn't get how to make it work outside of vsc. 
There was some work done to make it work in neovim, see https://github.com/moetelo/twiggy/issues/5.

Having an editor-independent LS is one of the good goals here.
